### ISSUE TITLE
Checksum does not work properly

### ISSUE THREAD

**Issue by joew46167** [turnerhayes/xpuz#3]
Hello

Your checksum for the puz parser (src/parsers/puz.js) is incorrect.

The .puz standard says that the notes only get included in version 1.3 and higher. As a result, I am unable to parse my version 1.2 puz files.  So in  src/parsers/puz.js at line 435 you need to add a check for the version number before you add the notes into the magic number checksum.

I attempted to make a fix and have a pull request, but apparently I did it incorrectly.

**Comment by turnerhayes** [comment]
Thanks for filing this issue! Where do you find the .puz standard documentation? I looked at [this](https://code.google.com/archive/p/puz/wikis/FileFormat.wiki) and it doesn't mention the version difference. Do you have a sample 1.2 .puz file that you could attach for me to test with?

**Comment by joew46167** [comment]
OK, I admit, I hadn't closely read the link you supplied before today.  However, because I was having checksum issues, I did follow the link from your readme (Many thanks to https://github.com/alexdej/puzpy for information on checksums and extensions.) to compare checksum code.  This is a snippet of code from puzpy:

        # notes included in global cksum starting v1.3 of format
        if self.version_tuple() >= (1,3) and self.notes:
            cksum = data_cksum(self.notes.encode(ENCODING) + b'\0', cksum)

I have a very simple file that I use for testing.  It makes it easier to do the checksum by hand :)
[joe.zip](https://github.com/turnerhayes/xpuz/files/3416680/joe.zip)

There are 2 files.  Both are the same puzzle.  Both are version 1.2.

joe.puz has a note and the checksum fails.
joe without note.puz does not have a note, and the checksum passes.

**Comment by joew46167** [comment]
I did a little more digging.  At your link to the manual I clicked the download innk, and I downloaded lib-1.1.0.tar.gz and looked into it.  Since it was a pain to get to, I have included only the 2 files that were of interest there - the puz spec and the versuion 1.2 test file there.

You'll see that in the puz spec, there is no checksum done for the notes section.  

I for one believe this to be accurate, as there wasn't another update for almost 3.5 years.

[doc.zip](https://github.com/turnerhayes/xpuz/files/3416761/doc.zip)

**Comment by turnerhayes** [comment]
Published a fix in 1.2.0 (should be on NPM now). Let me know if it's still broken!

**Comment by joew46167** [comment]
Thank you very much - I am able to load my puzzles with notes now.  👍 

However, theoretically, it's still broken.

I don't have a file with which to prove it, but when I look at this code:

```
	if (versionParts[0] >= 1 && versionParts[1] >= 3) { // eslint-disable-line no-magic-numbers
		if (puzzleData.notes) {
			checksum = _doChecksum(iconv.encode(puzzleData.notes + "\0", PUZReader.ENCODING), checksum);
		}
	}

```
I see that in a version 2.0 .puz file (if that ever exists) the notes will not be in the checksum - versionParts[1] >= 3 will be false making the entire if statement false. 

My guess is that 2.0 would require a rewrite anyway and it won't truly ever be an issue that people would see.  But it might be something that you don't find easily in that rewrite, too.  I wouldn't say a change is 100% required at this point, so treat it as you see fit.

**Comment by turnerhayes** [comment]
Ah, good point! I wanted a quick-and-dirty version check without having to implement full semver comparison (or add a dep). Probably should be something like `if (versionParts[0] > 1 || versionParts[1] >= 3)`.

But I think you're right about 2.0 probably needing a more extensive rewrite (it also seems pretty unlikely that'll come anytime soon, it seems to be pretty static by now).

**Comment by joew46167** [comment]
I don't know if there ever was, for instance, a version 0.3 - that would also cause issues in your modified version.
But for now if it were me I'd probably leave it as it is.
    On Tuesday, July 23, 2019, 10:18:07 PM EDT, Turner Hayes <notifications@github.com> wrote:  
 
 
Ah, good point! I wanted a quick-and-dirty version check without having to implement full semver comparison (or add a dep). Probably should be something like if (versionParts[0] > 1 || versionParts[1] >= 3).

But I think you're right about 2.0 probably needing a more extensive rewrite (it also seems pretty unlikely that'll come anytime soon, it seems to be pretty static by now).
